diff -Naur -x '*.o' -x '*.a' -x '*.orig' -x '*.patch' -x '*.bl' -x '*.ps' -x '*.dat' /tmp/Xfoil/bin/Makefile_gfortran ./bin/Makefile_gfortran
--- /tmp/Xfoil/bin/Makefile_gfortran	2012-03-06 21:33:23.000000000 -0800
+++ ./bin/Makefile_gfortran	2025-08-14 14:09:08.063420842 -0700
@@ -6,7 +6,7 @@
 
 
 SHELL = sh
-BINDIR = /home/codes/bin/
+BINDIR = /usr/local/bin/
 #BINDIR = .
 
 PROGS = xfoil pplot pxplot
@@ -119,8 +119,9 @@
 CHK = 
 #CHK = -fbounds-check -finit-real=inf -ffpe-trap=invalid,zero,denormal
 DBL = -fdefault-real-8
-FFLAGS = -O $(CHK) $(DBL)
-FFLOPT = -O $(CHK) $(DBL)
+LEGACY = -fallow-argument-mismatch -std=legacy
+FFLAGS = -O $(CHK) $(DBL) $(LEGACY)
+FFLOPT = -O $(CHK) $(DBL) $(LEGACY)
 FTNLIB =
 
 PLTOBJ = ../plotlib/libPlt_gDP.a 
@@ -141,19 +142,15 @@
 
 xfoil: $(XFOILOBJ) $(XUTILOBJ) $(OSOBJ)
 	$(FC) -o xfoil $(XFOILOBJ) $(XUTILOBJ) $(OSOBJ) $(PLTOBJ) $(PLTLIB) $(FTNLIB)
-	$(INSTALLCMD) xfoil $(BINDIR)
 
 pxplot:	$(PXPLOTOBJ) $(XUTILOBJ)
 	$(FC) -o pxplot $(PXPLOTOBJ) $(XUTILOBJ) $(PLTOBJ) $(PLTLIB) $(FTNLIB)
-	$(INSTALLCMD) pxplot $(BINDIR)
 
 pplot:	$(PPLOTOBJ) $(XUTILOBJ)
 	$(FC) -o pplot $(PPLOTOBJ) $(XUTILOBJ)  $(PLTOBJ) $(PLTLIB) $(FTNLIB)
-	$(INSTALLCMD) pplot $(BINDIR)
 
 blu: blu.o profil.o
 	$(FC) -o blu blu.o profil.o
-	$(INSTALLCMD) blu $(BINDIR)
 
 
 blu.o: $(SRC)/blu.f
diff -Naur -x '*.o' -x '*.a' -x '*.orig' -x '*.patch' -x '*.bl' -x '*.ps' -x '*.dat' /tmp/Xfoil/plotlib/Makefile ./plotlib/Makefile
--- /tmp/Xfoil/plotlib/Makefile	2012-12-16 20:10:15.000000000 -0800
+++ ./plotlib/Makefile	2025-08-13 16:59:01.217009312 -0700
@@ -68,7 +68,7 @@
 
 ###-------------------------------------------------------------------------
 ### Set compiler, compiler flags, name of output object library
-include ./config.make
+include ./config.make.gfortranDP
 
 
 ###-------------------------------------------------------------------------
